services:
  # Solo la base de datos en Docker
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gimnasio_db
      POSTGRES_USER: gimnasio_user
      POSTGRES_PASSWORD: gimnasio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: